### PR TITLE
Fix #195. Allow seven segment IPv6 with single elided segment

### LINKED ISSUE #195: Seven-segment IPv6 addresses not handled properly
**Describe the bug**
The IPv6 parser seems to have misread the spec; the IPv6 string `[E873:4eC5:eBc9:9e97:6BcE:998C:95AD::]` is a valid `IPv6address` object under RFC 3986, matching the last ABNF rule in the list on page 20:

```
IPv6address =
    <other options>
    / [ *6( h16 ":" ) h16 ] "::"

h16 = 1*4HEXDIG
```

But parsing this causes an error that says there must be exactly eight or fewer than six hex pieces, which I think must be a misunderstanding since this section of the document is very confusing.

**To Reproduce**
```scala
val url = "https://[E873:4eC5:eBc9:9e97:6BcE:998C:95AD::]/"
Url.parse(url)
```

```
[info]     Message: IPv6 has too many pieces. Must be either exactly eight hex pieces or fewer than six hex pieces with a '::'    
```

### PR DESCRIPTION
**Pull request by theon**

### CODE REVIEW

File: shared/src/main/scala/io/lemonlabs/uri/parsing/UrlParser.scala [hunk 1]
```diff
@@ -257,14 +257,14 @@ class UrlParser(val input: ParserInput)(implicit conf: UriConfig = UriConfig.def
   val extractFullIpv6 = (pieces: immutable.Seq[String]) => IpV6.fromHexPieces(pieces)
 
   val extractIpv6WithEluded = (beforeEluded: immutable.Seq[String], afterEluded: immutable.Seq[String]) => {
```
Comment (theon) [inline shared/src/main/scala/io/lemonlabs/uri/parsing/UrlParser.scala:259]: `Eluded` is a typo here and should be `Elided`. Can't change it now because it breaks binary compatibility as mima. I will fix at the next big version bump and also make these fields `private` as they need not be public.
